title: Miliamperios
show_dir_listing: false
url: https://miliamperios.github.io

# Build settings
future: false
incremental: true
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    fenced_code_blocks: true
sass:
  style: compressed
plugins:
  - jekyll-feed
# Exclude this from being processed by Jekyll
exclude:
  - vendor
  - .sass-cache
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .ruby-version

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: base
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: post
